### ISSUE TITLE
Unsupported OpenGL Version (OpenGL ES 2.0), OpenGL 1.2 is required

### ISSUE THREAD

**Issue by pmjdebruijn** [cdev-tux/q3lite#10]
I'm trying to crosscompile q3lite from an x86 machine to arm, using buildroot (which is an embedded linux system development suite).

I'm calling make directly (not using make-raspberrypi.sh):
[q3lite-build.txt](https://github.com/cdev-tux/q3lite/files/2730773/q3lite-build.txt)

But q3lite isn't starting:
[q3lite-glesissue.txt](https://github.com/cdev-tux/q3lite/files/2730774/q3lite-glesissue.txt)

Throwing the message:
"Unsupported OpenGL Version (OpenGL ES 2.0), OpenGL 1.2 is required"

Would you mind taking a look to see if I'm missing something?

**Comment by cdev-tux** [comment]
Hello,

I’ll try to help you out if I can; I don’t have any buildroot experience.  I see a few issues from the log file. 

If you’re compiling for a pi zero or pi 1, then ARCH=arm.  If you’re compiling for a pi 2 or pi 3, then ARCH=armv7l.

Try running the game as the pi user instead of root.  The game needs to be able to find the supplied autoexec.cfg file, which normally resides in ~/.q3a/baseq3/.  You can copy the autoexec.cfg file from the source code directory in /misc/q3lite to ~/.q3a/baseq3/.

SDL is reporting GL_VERSION=OpenGL ES 2.0, and it should be reporting GL_VERSION=OpenGL ES-CM 1.1, so make sure that you are booting the pi using the Broadcom legacy driver, and not the OpenGL desktop driver.

I hope that helps, please let me know if you have any other questions.

**Comment by cdev-tux** [comment]
I'm going to close this issue, please feel free to reopen if needed.  Thanks.
