### ISSUE TITLE
Mirrors are black

### ISSUE THREAD

**Issue by jacobo-mc** [cdev-tux/q3lite#16]
Whenever there should be a mirror i see a black surface instead.

**Comment by cdev-tux** [comment]
Hello,

Set r_fastsky to zero to see through portals and to see reflections in mirrors. This slows down the framerate quite a bit, so that’s why it’s turned off by default. You can bind a key to toggle the setting on and off. To see reflections in mirrors change the setting in autoexec.cfg or in the console:

r_fastsky "0"

https://github.com/cdev-tux/q3lite/blob/dev/misc/q3lite/autoexec.cfg#L547-L548

**Comment by jacobo-mc** [comment]
you should put this in the FAQ

**Comment by cdev-tux** [comment]
I added this to the FAQ (2.10).  Thanks!
