### ISSUE TITLE
Compiling fails under Raspberry Pi OS Bullseye

### ISSUE THREAD

**Issue by T0bi79** [cdev-tux/q3lite#19]
I used this tutorial https://pimylifeup.com/raspberry-pi-quake-3/

- Under Buster Lite it succeeds.
- Under Bullseye Lite it fails:

REF_CC code/renderergles1/tr_animation.c
In file included from code/renderergles1/../renderercommon/qgl.h:38,
                 from code/renderergles1/../renderercommon/tr_common.h:34,
                 from code/renderergles1/tr_local.h:38,
                 from code/renderergles1/tr_animation.c:30:
code/SDL2/include/SDL_opengles.h:33:10: fatal error: GLES/gl.h: No such file or directory
   33 | #include <GLES/gl.h>
      |          ^~~~~~~~~~~
compilation terminated.

**Comment by cdev-tux** [comment]
I can't support 3rd-party install guides, please see the [Compiling and Installation Guide](https://github.com/cdev-tux/q3lite/wiki/Compiling-Install-Guide) in the Wiki. There have been major changes to the Raspberry Pi OS with Bullseye, so for now I would recommend keeping an SD card with Buster on it for playing Q3lite. I spent a few days looking at the issue and don't currently have a solution. Since this type of project is volunteer work, I won't have time to spend on it anytime soon. However, I would encourage you and others to continue to work on this. Here's a few things to check:  

Q3lite currently only supports Pi 0,1,2,3 using GLES. (no Pi 4 or Pi Zero 2 W support)  

Make sure you are using the legacy GLES driver selection with 'sudo raspi-config'. Advanced Options > GL Driver.  

Follow the Compiling and Installation Guide and ensure that you have all prerequisites installed.  

Maybe @jdonald or someone else has some insight as to why it fails to compile on Bullseye? (Khronos headers instead of Buster's GLES headers?)

**Comment by jdonald** [comment]
I got around to trying out Bullseye, and successfully built q3lite.

For some reason `/opt/vc/include/` is not present by default and not in any apt packages, leading to the error shown above. You can download it from https://github.com/raspberrypi/firmware/tree/master/opt/vc/include and then `sudo bash make-raspberrypi.sh` works fine.

**Comment by greyfrontier** [comment]
Hi. I was able to compile without issues on my Pi 1 running Bullseye. I just can’t get it to start. Do I need to revert to Buster? When I’m using the non OpenGL driver (which is the same method I got Q3Lite to work on Buster) it gives me a failure to initialize the OpenGL ES1 renderer. 
I also got an undefined symbol (glactivetexture) as well. 
![0ECBFA66-C76A-41DC-9377-DD0AC775F1D6](https://user-images.githubusercontent.com/104728682/166154339-5b474a82-bb9d-4fc5-88da-ba8b8c378c23.jpeg)

**Comment by azhkprtw** [comment]
Hi. I was able to compile without issues on my Pi 1 running Bullseye. I just can’t get it to start. Do I need to revert to Buster? When I’m using the non OpenGL driver (which is the same method I got Q3Lite to work on Buster) it gives me a failure to initialize the OpenGL ES1 renderer.
I also got an undefined symbol (glactivetexture) as well.
![F693AB54-A6E1-44E9-A6C9-33E6D15A8EB3](https://user-images.githubusercontent.com/104728682/166154442-7ca22895-9e15-49aa-aa2c-61499bec198c.jpeg)

**Comment by jdonald** [comment]
Hi @greyfrontier sorry that I didn't actually do a runtime test for my February comment. For expedience I built it only on a Pi 4 at the time, and providing something that doesn't actually run was pretty irresponsible of me.

I've looked closer on a Pi 3B+ now. First thing I encountered after doing `sudo raspi-config` to enable the legacy driver is that the whole /opt/vc folder, not merely /opt/vc/include, seems to be missing on the default image so I had to download that.

Next, it seems to me the build makes assumptions of /opt/vc/lib being in the default linker path as it had been for buster and prior, so we currently don't have the right flags to even add it with the -rpath flag. The quickest workaround for this is to do:
```
sudo ldconfig /opt/vc/lib
```
prior to building.

Once I do that it gets past the runtime linker error, but I hit a black screen. I then checked other legacy examples in /opt/vc/src/hello_pi and found hello_triangle and hello_teapot no longer render anything. Unless I'm missing some obvious step it seems GLES rendering with the legacy driver does not work on bullseye, so there may not be any viable path forward for q3lite. And if that's the case, I can only suggest the alternative:
```
sudo apt install quake3
```
with the Mesa driver, although that'll probably require something newer than a Pi 1.

**Comment by azhkprtw** [comment]
Hey thank you for getting back to me, I'm sorry for the delay. I even tried doing an in place upgrade to Bullseye - but yeah! hahaha I think it's because I have the Pi 1 

Still impressive to know I can get it running on Buster when I followed the excellent instructions.. I do appreciate everything!!

**Comment by cdev-tux** [comment]
Due to all of the changes in Raspberry Pi OS and the graphics drivers/subsystem, the current version won’t run on anything newer than Buster.
